FROM maxdotio/mighty-sentence-transformers:0.9.8

ENV MIGHTY_PORT ${MIGHTY_PORT}
CMD ["sh", "-c", "/mighty/mighty --sentence-transformers --model=sentence-transformers/multi-qa-MiniLM-L6-cos-v1 --port=${MIGHTY_PORT}"]
